---
title: "Aquatics"
---

```{r setup, echo = FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
library(ggiraph)
library(patchwork)
library(tidyverse)
library(neon4cast)
library(score4cast)
source("R/plot-utils.R")
```

```{r include=FALSE}
cutoff <- as.character(Sys.Date() - 30)
combined <- arrow::open_dataset("cache/parquet/aquatics") |>
  filter(date >= cutoff)

```

## Most recent forecasts

Below is the latest forecasts for which we have at least 10 observations. Mouse over to see the team id, scroll to zoom.

```{r}
sites <- combined |> distinct(site_id) |> collect() |> pull(site_id)
## with at least n observations to compare!
n_data <- 10
who <- combined |> filter(!is.na(observation)) |> summarise(has_data = max(reference_datetime)) |> collect()
ref <- as.character ( as.Date(who$has_data[[1]]) - n_data )
ex <- combined |> filter(reference_datetime == ref) 

```

::: panel-tabset
## Oxygen

```{r}
ex |> filter(reference_datetime == ref, variable == "oxygen") |> forecast_plots()
```

## Temperature

```{r}
ex |> filter(reference_datetime == ref, variable == "temperature") |> forecast_plots()
```

## Chlorophyll-A


<!-- Heading 1: navbar -->

::: panel-tabset
## Oxygen

```{r}
leaderboard_plots(combined, "oxygen")
```

## Temperature

```{r}
leaderboard_plots(combined, "temperature")
```

## Chlorophyll-A

```{r}
leaderboard_plots(combined, "chla")
```
:::


