---
title: "NEON4CAST Dashboard"
output:
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: 
      version: 4
      bootswatch: lux
    source_code: "https://github.com/eco4cast/neon4cast-dashboard"
    navbar:
    - { title: "Phenology", icon: "fas fa-leaf", href: "phenology", target: "_blank"}
    - { title: "Aquatics", icon: "fa fa-tint", href: "aquatics", target: "_blank"}
    - { title: "Terrestrial", icon: "fa fa-thermometer-4", href: "terrestrial", target: "_blank"}
    - { title: "Ticks", icon: "fa fa-search", href: "ticks", target: "_blank"}
    - { title: "Beetles", icon: "fas fa-bug", href: "beetles", target: "_blank"}

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE)
library(flexdashboard)
library(thematic)
library(ggiraph)
library(patchwork)
library(tidyverse)
library(neon4cast)
thematic::thematic_rmd()
```

```{r include=FALSE}
#combined <- read_csv("https://data.ecoforecast.org/analysis/combined_forecasts_scores.csv.gz")

source("R/combined_scores.R")
beetles <- combined_scores("beetles")
```

<!-- Heading 1: navbar -->


```{r}
## We will focus on sites with the most data.  A good number of sites stopped data collection during the pandemic, leaving teams without recent data to train on, and in many cases, without observations to score against.
df <- beetles %>% filter(time > as.Date("2019-01-01"), 
                         !is.na(observed))
top_sites <- df %>% 
  select(siteID, time) %>% distinct()  %>%
  count(siteID, sort=TRUE) %>% 
  pull(siteID) %>% head()

```



```{r}
richness_forecasts <-
  beetles %>% 
  filter( horizon > 30, target == "richness") %>% 
  group_by(time, siteID, team) %>%
  slice_min(horizon) %>% 
  na.omit() %>% 
  ungroup()

multipoint <- richness_forecasts %>% filter(team != "EFI_avg_null") %>% 
  count(siteID, team, sort=TRUE) %>% 
  filter(n>1) %>% select(-n)
inner_join(multipoint, richness_forecasts) %>%
  ggplot() +
  geom_point(aes(time, observed), size = .05) + 
   geom_ribbon_interactive(aes(x = time, ymin = lower95, ymax = upper95,
                               fill = team, data_id = team),
                               alpha = 0.2, show.legend=FALSE) +
  geom_line_interactive(aes(time, mean, col = team, data_id = team)) +
  facet_wrap(~siteID, ncol=1, scales = "free") + 
  ggtitle("30th day ahead")
```



```{r fill_scores}
null_filled <- beetles %>% # fill scores not working...
  fill_scores("EFI_ave_null") %>% 
  collect() %>% 
  mutate(time = as.Date(time), 
         forecast_start_time  = as.Date(forecast_start_time),
         horizon = as.integer(time - forecast_start_time))

scores <- null_filled %>%
  mean_scores()

```
