---
title: Phenology 
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

```{r setup}
library(ggiraph)
library(patchwork)
library(tidyverse)
library(neon4cast)
library(score4cast)
source("R/plot-utils.R")
```

```{r}
cutoff <- as.character(Sys.Date() - 30)
#combined <- combined_scores("phenology")
combined <- arrow::open_dataset("cache/parquet/phenology") |>
  filter(date >= cutoff,variable == "gcc_90") 
```

## Most recent forecasts


```{r}

sites <- combined |> distinct(site_id) |> collect() |> pull(site_id)

## with at least n observations to compare!
n_data <- 10
who <- combined |> filter(!is.na(observation)) |> summarise(has_data = max(reference_datetime)) |> collect()
ref <- as.character ( as.Date(who$has_data[[1]]) - n_data )

ex <- combined |> filter(reference_datetime == ref) 
```


::: panel-tabset
## Sites 1 - 6

```{r}
ex |> 
  filter(site_id %in% sites[1:6]) |> 
  collect() |> 
  forecast_plots()
```

## 7-12

```{r}
combined |> filter(reference_datetime == ref, site_id %in% sites[7:12]) |> forecast_plots()
```

## 13 - 18

```{r}
combined |>  filter(reference_datetime == ref, site_id %in% sites[13:18]) |>   forecast_plots()
```
:::

## Leaderboard


```{r}
leaderboard_plots(combined, "gcc_90")
```
