---
title: "NEON4CAST Dashboard"
output:
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: 
      version: 4
      bootswatch: lux
    source_code: "https://github.com/eco4cast/neon4cast-dashboard"
    navbar:
    - { title: "Phenology", icon: "fas fa-leaf", href: "phenology", target: "_blank"}
    - { title: "Aquatics", icon: "fa fa-tint", href: "aquatics", target: "_blank"}
    - { title: "Terrestrial", icon: "fa fa-thermometer-4", href: "terrestrial", target: "_blank"}
    - { title: "Ticks", icon: "fa fa-search", href: "ticks", target: "_blank"}
    - { title: "Beetles", icon: "fas fa-bug", href: "beetles", target: "_blank"}    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE)
library(flexdashboard)
library(thematic)
library(ggiraph)
library(patchwork)
library(tidyverse)
library(neon4cast)
library(lubridate)
library(tools)
library(phenopix)
library(zoo)
thematic::thematic_rmd()
```

```{r include=FALSE}
#combined <- read_csv("https://data.ecoforecast.org/analysis/combined_forecasts_scores.csv.gz")
source("R/combined_scores.R")
combined <- combined_scores("phenology") %>% collect()
```

<!-- Heading 1: navbar -->



```{r}
sites <- c("BART", "CLBJ", "DELA", "GRSM", "HARV", "SCBI", "STEI", "UKFS")

greenness_forecasts <-
  combined %>%
  #filter(siteID %in% sites[-2]) %>%
  filter(theme == "phenology", target == "gcc_90",
         horizon > 30, time > as_date("2021-01-01"), time < (Sys.Date() + days(35))) %>% 
  group_by(time, siteID, team) %>%
  slice_min(horizon) %>% 
  ggplot() +
  geom_point(aes(time, observed), size = .05) + 
  geom_ribbon_interactive(aes(x = time, ymin = lower95, ymax = upper95,
                              fill = team, data_id = team, tooltip = team),
                          alpha = 0.2, show.legend=FALSE) +
  geom_line_interactive(aes(time, mean, col = team, 
                            tooltip = team, data_id = team), show.legend=FALSE) +
  labs(y = "greenness index (gcc 90)") +
  facet_wrap(~siteID, ncol=2) + 
  theme(axis.text.x = element_text( angle = 90, hjust = 0.5, vjust = 0.5)) +
  ggtitle("30th day ahead or longer prediction") 
```


```{r fill_scores}

null_filled <- combined %>% 
  filter(theme == "phenology", target == "gcc_90") %>% 
  fill_scores() %>% 
  collect() %>% 
  mutate(time = as.Date(time), 
         forecast_start_time  = as.Date(forecast_start_time),
         horizon = as.integer(time - forecast_start_time))

scores <- null_filled %>%
  mean_scores()

```
```{r}
###File to Calculate and Save Transition Dates for PhenoCam Sites

if(!file.exists("phenology_spring2021_transitions.csv")){

  
  ##Note: submittedForecasts comes from main script 
  
  site_names <- c("HARV", "BART", "SCBI", "STEI", "UKFS", "GRSM", "DELA", "CLBJ")
  allTransitions <- data.frame(matrix(ncol=13,nrow=length(site_names)))
  colnames(allTransitions) <- c("siteID","day15","value15","sd15","day50","value50","sd50","day85","value85","sd85","rangeLength",
                                "minimum","maximum")
  allTransitions$siteID <- site_names
  desiredTransitions <- c(0.15,0.5,0.85)
  
  for(s in 1:length(site_names)){
    subDat <- combined %>% 
      filter(siteID == site_names[s],
             time > as_date("2021-01-01"),
             time < as_date("2021-06-30"),
             team == "climatology",
             target == "gcc_90",
             time == forecast_start_time+1)
    
    
    #subDat <- subDat[subDat$time == (subDat$forecast_start_time+1),] ## only need each day once
    p <- zoo(na.approx(subDat$observed))
    
    outE <- ElmoreFit(p, uncert = TRUE) #Calculates seasonal fit
    
    transitionDys <- numeric()
    vls <- numeric()
    sds <- numeric()
    for(t in desiredTransitions){
      vl <- min(outE$fit$predicted)+t*diff(range(outE$fit$predicted))
      vls <- c(vls,vl)
      newDy <- min(which(outE$fit$predicted>vl))
      sds <- c(sds,sd(outE$uncertainty$predicted[newDy,]))
      transitionDys <- c(transitionDys,newDy)
    }
    # PhenoPlot(outE,"GCC",main=site_names[s],ylab="GCC",xlab="Day of Year")
    # points(p,pch=20)
    # abline(v=transitionDys,col="red")
    allTransitions[s,c(2,5,8)] <- transitionDys + lubridate::yday(subDat$time[1]) - 1
    allTransitions[s,c(3,6,9,11)] <- c(vls,diff(outE$fit$sf))
    allTransitions[s,c(4,7,10)] <- sds
    allTransitions$minimum[s] <- min(outE$fit$predicted)
    allTransitions$maximum[s] <- max(outE$fit$predicted)
  }
  
  allTransitions2 <-  allTransitions %>% 
    select(siteID,  day15, day50, day85) %>% 
    mutate(day50 = as_date("2020-12-31") + days(day50),
           day15 = as_date("2020-12-31") + days(day15),
           day85 = as_date("2020-12-31") + days(day85))
  
  write_csv(allTransitions2, "phenology_spring2021_transitions.csv")
}else{
  allTransitions2 <- read_csv("phenology_spring2021_transitions.csv")
}

null_filled <- left_join(null_filled, allTransitions2)

```

```{r score_by_horizon}
score_by_horizon <- null_filled %>%
  filter(time == day50) %>% 
  mutate(horizon = -horizon) %>% 
  group_by(theme, target, team, horizon) %>%  # average over siteID
  summarise(mean_crps = mean(filled_crps, na.rm =TRUE),
            mean_logs = mean(filled_logs, na.rm = TRUE),
            .groups = "drop") %>%
  pivot_longer(cols = c("mean_crps", "mean_logs"), 
               names_to = "metric", values_to="score") %>%
  filter(metric == "mean_crps") %>%
  filter(!is.na(score)) %>% 
  ggplot(aes(horizon, score, col=team, shape=metric)) + 
  geom_line_interactive(aes(tooltip = team, data_id = team),
                        lwd = 1, show.legend=FALSE) + 
    geom_point_interactive(aes(tooltip = team, data_id = team),
                        lwd = 1, show.legend=FALSE) +
  labs(x = "days prior to site-specific green out", title = "site-level mean score")

```


```{r score_by_time}
score_by_time <- null_filled %>%
  mutate(relative_date = as.numeric(time - day50)) %>% 
  filter(horizon > 30, time < as_date("2021-06-30")) %>% 
  group_by(theme, target, team, relative_date) %>%  # average over siteID
  summarise(mean_crps = mean(filled_crps, na.rm =TRUE),
            .groups = "drop") %>% 
  filter(!is.na(mean_crps)) %>% 
 # filter(team %in% best) %>%
  ggplot(aes(relative_date, mean_crps, col=team)) + 
  geom_line_interactive(aes(tooltip = team, data_id = team),
                        show.legend = FALSE, lwd=1) + 
    geom_point_interactive(aes(tooltip = team, data_id = team),
                        show.legend = FALSE, lwd=1) +
  labs(x = "days relative to site-specific green out", y = "score")
```

```{r score_by_site}
score_by_site  <- null_filled %>%
  group_by(theme, target, team, siteID) %>%  # average over siteID
  summarise(mean_crps = mean(filled_crps, na.rm =TRUE),
            mean_logs = mean(filled_logs, na.rm = TRUE),
            .groups = "drop") %>% 
  pivot_longer(cols = c("mean_crps", "mean_logs"), 
               names_to = "metric", values_to="score") %>%
  filter(metric == "mean_crps") %>%
  ggplot(aes(metric, score, fill=team)) + 
  geom_col_interactive(aes(tooltip = team, data_id = team),
                       position="dodge", show.legend = FALSE) + 
  facet_wrap(~siteID)


  
```

```{r score_total}
score_total  <- null_filled %>%
  group_by(theme, target, team) %>%  # average over siteID
  summarise(mean_crps = mean(filled_crps, na.rm =TRUE),
            mean_logs = mean(filled_logs, na.rm = TRUE),
            .groups = "drop") %>% 
  pivot_longer(cols = c("mean_crps", "mean_logs"), 
               names_to = "metric", values_to="score") %>%
  filter(metric == "mean_crps") %>%
  ggplot(aes(metric, score, fill=team)) + 
  geom_col_interactive(aes(tooltip = team, data_id = team),
                       position="dodge", show.legend = FALSE) +
  labs(x = "")


  
```

Section {.tabset}
-------------------------------------

### Greenness {data-height=2000 data.width=500}

Mouse over a trajectory to focus on a team. 
Activate zoom/pan with magnifying glass and then use mouse scroll to zoom.

```{r girafe, fig.width = 10, fig.height = 7.5}
ggob <- greenness_forecasts +
  (score_total) / 
  (score_by_horizon) /
  (score_by_time)
girafe(ggobj = ggob, width_svg = 10, height_svg = 7.5,
  options = list(
    opts_hover_inv(css = "opacity:0.03;"),
    opts_hover(css = "stroke-width:1;"),
    opts_zoom(max = 4)
  ))
```





### Redness {data-height=1500 data.width=500}

```{r redness, fig.width = 10, fig.height = 7.5}
redness <-
  combined %>%
  filter(siteID %in% sites[-2]) %>%
  filter(theme == "phenology", target == "rcc_90",
         horizon > 30, time > as.Date("2021-01-01")) %>% 
  group_by(time, siteID, team) %>%
  slice_min(horizon) %>% 
  ggplot() +
  geom_point(aes(time, observed), size = .1) + 
  geom_ribbon_interactive(aes(x = time, ymin = lower95, ymax = upper95,
                              fill = team, data_id = team, tooltip = team),
                          alpha = 0.2, show.legend=FALSE) +
  geom_line_interactive(aes(time, mean, col = team, 
                            tooltip = team, data_id = team), show.legend=FALSE) +
  facet_wrap(~siteID, ncol=2)

girafe(ggobj = redness, width_svg = 12, height_svg = 9,
  options = list(
    opts_hover_inv(css = "opacity:0.05;"),
    opts_hover(css = "stroke-width:2;"),
    opts_zoom(max = 4)
  ))
```  

### Statistics

#### Days remaining

```{r}
pheno_end_date <- as.Date("2021-12-31")
pheno_start_date <- as.Date("2021-02-01")
days <- (pheno_end_date - Sys.Date() ) 
max <- pheno_end_date - pheno_start_date
gauge(days, min = 0, max = max, symbol = '', gaugeSectors(
  success = c(81, max), warning = c(10, 3), danger = c(0, 2)
))
```



#### Teams

```{r}
total <- combined %>% filter(theme == "phenology") %>% select(team) %>% distinct() %>% count()
flexdashboard::valueBox(total)
```

#### Leaderboard (target: greeness)

```{r}
scores %>% filter(target == "gcc_90") %>% select(-target) %>% rmarkdown::paged_table(scores)
```




