---
title: "NEON4CAST Dashboard"
output:
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: 
      version: 4
      bootswatch: lux
    source_code: "https://github.com/eco4cast/neon4cast-dashboard"
    navbar:
    - { title: "Phenology", icon: "fas fa-leaf", href: "phenology", target: "_blank"}
    - { title: "Aquatics", icon: "fa fa-tint", href: "aquatics", target: "_blank"}
    - { title: "Terrestrial", icon: "fa fa-thermometer-4", href: "terrestrial", target: "_blank"}
    - { title: "Ticks", icon: "fa fa-search", href: "ticks", target: "_blank"}
    - { title: "Beetles", icon: "fas fa-bug", href: "beetles", target: "_blank"}

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE)
library(flexdashboard)
library(thematic)
library(ggiraph)
library(patchwork)
library(tidyverse)
library(neon4cast)
library(lubridate)
thematic::thematic_rmd()
```

```{r include=FALSE}
#combined <- read_csv("https://data.ecoforecast.org/analysis/combined_forecasts_scores.csv.gz")

source("R/combined_scores.R")
combined <- combined_scores("terrestrial_30min")
```

<!-- Heading 1: navbar -->


```{r}
## For some reason a bunch of teams aren't making predictions 7 days out..
nee_forecasts <- combined %>%
  filter(theme == "terrestrial_30min",
         horizon <= (35*24),
         time >= as_datetime("2021-02-01"),
         target == "nee") %>% 
  mutate(forecast_start_time = ifelse(forecast_start_time > as_date("2021-04-25") & forecast_start_time < as_date("2021-05-05"), as_date("2021-05-01"), as_date(forecast_start_time)),
         forecast_start_time = ifelse(forecast_start_time > as_date("2021-05-25") & forecast_start_time < as_date("2021-06-05"), as_date("2021-06-01"), as_date(forecast_start_time)),
         forecast_start_time = ifelse(forecast_start_time > as_date("2021-06-25") & forecast_start_time < as_date("2021-07-05"), as_date("2021-07-01"), as_date(forecast_start_time)),
         forecast_start_time = ifelse(forecast_start_time > as_date("2021-07-25") & forecast_start_time < as_date("2021-08-05"), as_date("2021-08-01"), as_date(forecast_start_time)),
         forecast_start_time = as_date(forecast_start_time)
         ) %>% 
  group_by(time, siteID, team, target, forecast_start_time) %>%
  filter(!is.na(mean)) %>% 
  #slice_min(horizon) %>% 
  ggplot() +
  geom_point(aes(time, observed), size = .05) + 
  geom_ribbon_interactive(aes(x = time, ymin = lower95, ymax = upper95,
                               fill = team, data_id = team),
                               alpha = 0.2, show.legend=FALSE) +
  geom_line_interactive(aes(x = time, y = mean, col = team, data_id = team), show.legend=FALSE) +
  facet_grid(siteID~forecast_start_time,scales = "free") + 
  ggtitle("Net Ecosystem Exchange") +
  theme(axis.text.x = element_text( angle = 90, hjust = 0.5, vjust = 0.5)) +
  labs(y = "umol/m3/sec")


```
```{r}
girafe(ggobj = nee_forecasts, width_svg = 10, height_svg = 7.5,
  options = list(
    opts_hover_inv(css = "opacity:0.03;"),
    opts_hover(css = "stroke-width:1;"),
    opts_zoom(max = 4)
  ))
```

