---
title: "Ticks"
---


```{r, setup, echo = FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE, eval=FALSE)
source("R/plot-utils.R")
 

```


```{r}
theme <- "ticks"
cutoff <- as.character(Sys.Date() - 120)
combined <- arrow::open_dataset(glue("cache/parquet/{theme}")) |>
  filter(date >= cutoff) |> collect()

```

## Most recent forecasts

```{r}
sites <- combined |> distinct(site_id) |> collect() |> pull(site_id)
## with at least n observations to compare!
n_data <- 30
who <- combined |> filter(!is.na(observation)) |> distinct(reference_datetime) |> arrange(desc(reference_datetime)) |> collect()
ref <- as.character (who[6,1]) # 
```

### "amblyomma_americanum"

::: panel-tabset
```{r}
richness <- combined |> 
  filter(reference_datetime == ref, variable == "amblyomma_americanum")
```

## Sites 1 - 8

```{r}
richness |>  filter(site_id %in% sites[1:8]) |> forecast_plots(ncol=4)
```

## Sites 9 - 16

```{r}
richness |> filter(site_id %in% sites[9:16]) |> forecast_plots(ncol=4)
```

## Sites 17 - 24

```{r}
richness |>  filter(site_id %in% sites[17:24]) |> forecast_plots(ncol=4)
```

## Sites 25 - 32

```{r}
richness |> filter(site_id %in% sites[25:32]) |> forecast_plots(ncol=4)
```

## Sites 33 - 40

```{r}
richness |>  filter(site_id %in% sites[33:40]) |> forecast_plots(ncol=4)
```

## Sites 41 - 47

```{r}
richness |> filter(site_id %in% sites[41:47]) |> forecast_plots(ncol=4)
```
:::

### "ixodes_scapularis"

::: panel-tabset
```{r}
abundance <- combined |> 
  filter(reference_datetime == ref, variable == "ixodes_scapularis")
```

## Sites 1 - 8

```{r}
abundance |>  filter(site_id %in% sites[1:8]) |> forecast_plots(ncol=4)
```

## Sites 9 - 16

```{r}
abundance |> filter(site_id %in% sites[9:16]) |> forecast_plots(ncol=4)
```

## Sites 17 - 24

```{r}
abundance |>  filter(site_id %in% sites[17:24]) |> forecast_plots(ncol=4)
```

## Sites 25 - 32

```{r}
abundance |> filter(site_id %in% sites[25:32]) |> forecast_plots(ncol=4)
```

## Sites 33 - 40

```{r}
abundance |>  filter(site_id %in% sites[33:40]) |> forecast_plots(ncol=4)
```

## Sites 41 - 47

```{r}
abundance |> filter(site_id %in% sites[41:47]) |> forecast_plots(ncol=4)
```
:::



## Leaderboard


::: panel-tabset
## richness

```{r}
leaderboard_plots(combined, "amblyomma_americanum")

```

## abundance

```{r}
leaderboard_plots(combined, "ixodes_scapularis")
```
:::

<!-- Consider adding site-by-site breakout on scores -->
