---
title: "NEON4CAST Dashboard"
output:
  flexdashboard::flex_dashboard:
    storyboard: true
    theme: 
      version: 4
      bootswatch: lux
    source_code: "https://github.com/eco4cast/neon4cast-dashboard"
    navbar:
    - { title: "Phenology", icon: "fas fa-leaf", href: "phenology", target: "_blank"}
    - { title: "Aquatics", icon: "fa fa-tint", href: "aquatics", target: "_blank"}
    - { title: "Terrestrial", icon: "fa fa-thermometer-4", href: "terrestrial", target: "_blank"}
    - { title: "Ticks", icon: "fa fa-search", href: "ticks", target: "_blank"}
    - { title: "Beetles", icon: "fas fa-bug", href: "beetles", target: "_blank"}    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE)
library(flexdashboard)
library(thematic)
library(ggiraph)
library(patchwork)
library(tidyverse)
library(DT)
thematic::thematic_rmd()
```

```{r include=FALSE, cache=TRUE}
source("R/combined_scores.R")
## TICKS HAVE NO OBSERVED DATA?
combined <- combined_scores("ticks")
filled_scores <- fill_scores(combined)
```


## {data-height: 350}

```{r}

leaderboard <-  combined %>% 
  group_by(variable, model_id) %>%
  summarise(crps = mean(crps),
            logs = mean(logs)) %>% 
  arrange(crps)
leaderboard %>% DT::datatable(fillContainer = FALSE, escape=FALSE)
```
<!-- Heading 1: navbar -->

```{r }
board1 <- 
leaderboard %>% filter(variable == "amblyomma_americanum") %>%
  pivot_longer(cols = c(crps, logs), names_to="metric", values_to="score") %>%
  ggplot(aes(model_id, score, fill=model_id, col=model_id)) + 
  geom_col_interactive(aes(tooltip = model_id, data_id = model_id), show.legend = FALSE) + 
  facet_wrap(~metric, scales = "free_y") + 
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank()) + 
  ggtitle("amblyomma_americanum forecasts")
```




***

No observed data seems to be available right now...